services:
  catalog_service:
    build: ./services/catalog_service
    
    ports:
      - "8001:8001"
    
    environment:
      - POSTGRES_CATALOG_URL=postgres://postgres:${DB_PASSWORD}@catalog_postgres:5432/catalog_db
    
    depends_on:
      catalog_postgres:
        condition: service_healthy

  order_cart_service:
    build: ./services/order_cart_service
    
    ports:
      - "8002:8002"
    
    environment:
      - REDIS_URL=redis://redis:6379
    
    depends_on:
      redis:
        condition: service_healthy

  customer_service:
    build: ./services/customer_service
    
    ports:
      - "8003:8003"
    
    environment:
      - POSTGRES_CUSTOMER_URL=postgresql+asyncpg://postgres:${DB_PASSWORD}@customer_postgres:5432/customer_db
      - JWT_SECRET=${JWT_SECRET}
    
    depends_on:
      customer_postgres:
        condition: service_healthy

  catalog_postgres:
    image: postgres:latest
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: catalog_db
    
    ports:
      - "5432:5432"
    
    logging:
      driver: "none"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 3

  customer_postgres:
    image: postgres:latest
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: customer_db
    
    ports:
      - "5433:5432"
    
    logging:
      driver: "none"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    
    ports:
      - "6379:6379"
    
    logging:
      driver: "none"
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
